"""empty message

Revision ID: 1fd6ac67a759
Revises: 8d4a211c8690
Create Date: 2025-10-16 22:56:42.351712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd6ac67a759'
down_revision = '8d4a211c8690'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accounts_user_id', table_name='accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_accounts_user_id', 'accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###
